service: github-backup-worker
frameworkVersion: "3"

plugins:
  # - serverless-plugin-typescript
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221
  logRetentionInDays: 30
  stage: dev
  region: ap-northeast-1
  timeout: 10

  stackTags:
    SERVICE: ${self:service}
    APP: ${self:service}
    STAGE: ${sls:stage}

  # iam:
  #   role:
  #     statements:
  #       - Effect: "Allow" # Systems Manager - Parameter Store
  #         Action:
  #           - "ssm:GetParameter"
  #         Resource:
  #           - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${self:custom.githubTokenParameterName}
  #           - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${self:custom.slackWebhookUrlParameterName}
  #       - Effect: "Allow" # KMS - Decrypt (for encrypted SSM parameters)
  #         Action:
  #           - "kms:Decrypt"
  #         Resource:
  #           - arn:aws:kms:ap-northeast-1:851725479915:key/16889861-08ea-4db8-beed-374d635ae972

  ecr:
    images:
      worker:
        path: ./worker
        platform: linux/x86_64

package:
  individually: true
  patterns:
    - "!**"

custom:
  infraStack: github-backup-infra
  repoOwner: mseninc
  githubToken: ${ssm:github-token}
  slackWebhookUrl: ${ssm:slack-webhook-url}
  workerImageName: serverless-${self:service}-${sls:stage}

functions: ${file(./functions.yml)}

resources: ${file(./resources.yml)}

stepFunctions: ${file(./step-functions.yml)}
