service: github-backup-infra
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221
  logRetentionInDays: 30
  stage: dev
  region: ap-northeast-1
  timeout: 10

  stackTags:
    SERVICE: ${self:service}
    APP: ${self:service}
    STAGE: ${sls:stage}

custom:
  cidr:
    company: 114.160.200.147/32
    vpc: 172.30.0.0/16
    publicSubnet1: 172.30.0.0/20
    publicSubnet2: 172.30.16.0/20
    privateSubnet1: 172.30.32.0/20
    privateSubnet2: 172.30.48.0/20

resources: ${file(./resources.yml)}
