service: github-backup
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221
  logRetentionInDays: 30
  stage: dev
  region: ap-northeast-1
  timeout: 10

  stackTags:
    SERVICE: ${self:service}
    APP: ${self:service}
    STAGE: ${sls:stage}

  ecr:
    images:
      lambda-ls-repos:
        path: ./lambda-ls-repos
        platform: linux/amd64
      lambda-repo-sync:
        path: ./lambda-repo-sync
        platform: linux/amd64

custom:
  infraStack: ${self:service}-infra

# params:
#   default: ${file(./params.${sls:stage}.yml)}

functions: ${file(./functions.yml)}
